Feature/shapeup 37 implementar feature de deletar usuario pelo email
shape-up-organization/back-end pull request #30
Opened 2023-03-10 00:02 UTC by Andrey-Benicchio

Analisem ai e aprovem

2023-03-10 14:35 UTC, gabrieldasilvadev requested changes
Executar as mudanças propostas nos comentários

2023-03-10 14:35 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/input/web/controller/UserController.java
> +import org.springframework.web.bind.annotation.*;
Essa abordagem de import, eh chamada de wildcard imports. Ela prejudica o desempenho de build do projeto, execucao de testes que precisam subir o contexto do spring, como, testes de componente e de integracao, tambem deixa o projeto mais pesado na hora de iniciaza-lo.

Para remover, siga esses passos:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206203659-Turn-off-Wildcard-imports-
https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-imports

2023-03-10 14:35 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/user/UserPersistenceAdapter.java
> +     userRepositoryJpa.deleteByEmail(email);
caso o email do usuario nao exista na nossa base de dados, qual erro temos que retornar para o front?
eh necessario validarmos os cenarios de falha. Ainda nao temos todas as trativas necessarias, mas ja existe no projeto metodos tratando de email ja existente. E caso surja oportunidade, crie uma validacao.

2023-03-12 18:36 UTC, Andrey-Benicchio commented on src/main/java/br/com/shapeup/adapters/output/integration/user/UserPersistenceAdapter.java
> +     userRepositoryJpa.deleteByEmail(email);
nesse caso o delete , ele nao deve retornar apenas o NO_CONTENT, pois se o objeto que ele esta procurando existir, ele apenas deleta e retorna o NO_CONTENT, caso nao exista ele tambem retorna isso pois nao teve oque deletar

2023-03-12 19:10 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/user/UserPersistenceAdapter.java
> +     userRepositoryJpa.deleteByEmail(email);
NO_CONTENT, esta relacionado com HTTP Status Code, nao com excecao que o back-end(servidor) ira mandar para o front-end(Cliente).
https://www.devmedia.com.br/http-status-code/41222
https://www.devmedia.com.br/tratando-excecoes-em-java/25514
Esses dois artigos explicam sobre os dois.

Apos entender do que se trata um status code. Pense no front-end, ele ira receber/saber apenas o que nos mandarmos para eles, nos dois casos, se retornamos NO_CONTENT(204), como ele ira saber se deu certo ou errado?
No artigo acima sobre HTTP Status Codes, ele explica que a familia 2xx, trata de casos de sucesso, logo, invalidando a possibilidade de usar como cenario de falha.

Exceptions, trata de possiveis cenarios em que um determinado fluxo(no caso, delecao do usuario) fuja do caminho de sucesso, que no caso, é deletar usuario, por exemplo, quero abrir uma conta no banco, mas o CPF que eu informo ja está cadastrado, o servidor retorna uma exception para o front-end informar para o usuario o que deu de errado.

2023-03-13 01:17 UTC, gabrieldasilvadev approved these changes

2023-03-13 01:17 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/input/web/controller/UserController.java
>  import org.springframework.web.bind.annotation.*;
Ainda esta importando como wildcard

https://www.baeldung.com/java-wildcard-imports
https://www.youtube.com/watch?v=pqXpxkosuxw

2023-03-13 01:17 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/user/UserPersistenceAdapter.java
> +     userRepositoryJpa.deleteByEmail(email);
![image](https://user-images.githubusercontent.com/70338009/224572144-fe7b46d8-59df-4479-82ca-ded1e123268f.png)

Esse metodo aqui, retorna true caso o usuario **EXISTA** no banco de dados, no seu caso, vc quer deletar apenas se o usuario existir, certo?
entao, pense em qual exception vc tem que lancar?
![image](https://user-images.githubusercontent.com/70338009/224572212-45abc1dc-4140-4c75-abcc-5093d1bd9b25.png)

A gente tem essa exception ja pronta que trata disso. Voce precisa validar o retorno do BOolean do jpa e lancar essa exception

2023-03-13 01:17 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/user/UserPersistenceAdapter.java
> +     userRepositoryJpa.deleteByEmail(email);
da um git pull origind develop, para vc pegar as mudancas da eduarda, creio que nao vai mudar nada no seu codigo, mas se der conflito nas branchs, me avisa aqui ou no discord (discord eu vejo mais rapdio kkk). ai eu te ensino a resolver conflitos de branch no intellij

2023-03-13 01:17 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/input/web/controller/UserController.java
>  import org.springframework.web.bind.annotation.*;
Essa paret aqui, observe no github que eu marco a linha do codigo, o wildcard como falavam nos posts eh a questao desse **".*"**. Ele importa tudo que esta dentro de " org.springframework.web.bind.annotation " isso afeta a performance, entao, usando o single import, onde importamos somente oq precisamos, vc tem que remover esse * vai ficar uns codigos vermelhos, ai vc precisa abertar alt enter e importar

2023-03-13 01:18 UTC, gabrieldasilvadev approved these changes

2023-03-13 01:25 UTC, merged