Feature/shapeup 71 criar endpoint para valida o de username j existente
shape-up-organization/back-end pull request #47
Opened 2023-03-25 18:38 UTC by Andrey-Benicchio

criação do endpoint de validação e userExistByUserName

2023-03-27 13:47 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/auth/AuthGateway.java
> +    Boolean validateUserName(String username);
Esse método não é para estar aqui. E não faz sentido, e causará problema na aplicação, se o usuário faz login, o usuário dele TEM QUE existir, se isso ficar assim, ele nunca vai conseguir fazer login...

2023-03-27 13:47 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/auth/AuthAdapter.java
> +        Boolean userExists = userRepositoryJpa.existsByUsername(username);
Repetição desnecessária de código. O método validateUserExistsByUserNameInDataBase, já trata disso.

2023-03-27 13:47 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/auth/AuthAdapter.java
> +        validateUserExistsByUserNameInDatabase(userAuthRegisterRequest.getUsername());
Esse método não é para estar aqui. A validação do username é outro endpoint.

2023-03-27 14:04 UTC, Andrey-Benicchio commented on src/main/java/br/com/shapeup/adapters/output/integration/auth/AuthGateway.java
> +    Boolean validateUserName(String username);
pra onde esse metodo tem que ir então?

2023-03-27 16:38 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/auth/AuthGateway.java
> +    Boolean validateUserName(String username);
no metodo do endpoint que verfica o username username.

2023-03-27 16:51 UTC, eduardaclx requested changes

2023-03-27 16:51 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/input/web/controller/AuthController.java
> +    @GetMapping("/{username}")
seria mais intuitivo pro front o endpoint ter um nome, como validate-username, não só um get vazio

a chamada desse endpoint ficaria assim: ..../auth/eduarda  não fica claro que é um endpoint que verifica um username, saca?

se estivesse no /users, faria um pouco mais de sentido, mas como esse endpoint é no /auth, o nome do endpoint não fica claro para sinalizar pra que ele serve

2023-03-27 16:51 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/output/integration/auth/AuthAdapter.java
> +
é detalhezinho besta, mas sempre bom apagar essas linhas a mais, e os imports que não estão em uso

ajuda a manter a padronização do código, se estiver em dúvida quando deve ou não apagar uma linha ou adicionar, da uma olhada no código da classe e em classes semelhantes

2023-03-29 16:34 UTC, gabrieldasilvadev approved these changes

2023-03-29 16:34 UTC, gabrieldasilvadev approved these changes

2023-03-29 19:38 UTC, eduardaclx approved these changes

2023-03-29 19:46 UTC, merged