Shapeup 87 implementar websocket na aplicacao com endpoint de chat 2
shape-up-organization/back-end pull request #59
Opened 2023-04-04 20:12 UTC by gabrieldasilvadev

2023-04-04 21:12 UTC, eduardaclx requested changes

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/input/web/controller/request/user/UserBirthRequest.java
> +    private String birth;
como dito em aula, por favor apague as messages

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/input/web/controller/request/user/UserCellphoneRequest.java
> +}
essa classe é necessária?

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/input/web/controller/request/user/UserLastNameRequest.java
apagar por favor

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/input/web/controller/request/user/UserNameRequest.java
apagar por favor

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/output/integration/friend/FindFriendshipAdapter.java
> +    public Boolean existsByUsernameSenderAndUsernameReceiver(String usernameSender, String usernameReceiver) {
o nome desse método não ficou intuitivo, pelo contexto da classe da para entender, porém exige esforço mental

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/output/integration/friend/FindFriendshipAdapter.java
> +
apaga a linha ai man kkkkk

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/output/integration/friend/FriendshipAdapter.java
> +}
depois abre um débito técnico no jira com a feature de não aceitar o pedido de amizade

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/output/integration/profile/ProfilePictureAdapter.java
> +        });
esse método de encontrar pelo email é necessário? pois para gerar um JWT, já foi verificado a existência desse email no banco

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/output/repository/model/chat/Message.java
> +import lombok.*;
por que ta assim?

2023-04-04 21:12 UTC, eduardaclx commented on src/main/java/br/com/shapeup/core/usecase/user/UserPersistanceUsecase.java
> +
apaga a linha por favor

2023-04-05 04:00 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/friend/FindFriendshipAdapter.java
> +    public Boolean existsByUsernameSenderAndUsernameReceiver(String usernameSender, String usernameReceiver) {
![image](https://user-images.githubusercontent.com/70338009/229977779-d660fabc-826a-4a3a-9524-3fdd2c898ac6.png)
Valida se o pedido de amizade ainda nao foi enviado.

2023-04-05 04:06 UTC, gabrieldasilvadev commented on src/main/java/br/com/shapeup/adapters/output/integration/profile/ProfilePictureAdapter.java
> +        });
Entao, realmente, nao precisaria encontrar pelo email, mas eu uso esse metodo para retornar o usuario e passar como parametro para o metodo que faz o upload para o S3. Acho que validar ai eh consequencia.
![image](https://user-images.githubusercontent.com/70338009/229978396-ac249981-4cd8-4f20-b7f1-e58e6f23f59a.png)

2023-04-05 12:42 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/output/integration/friend/FindFriendshipAdapter.java
> +    public Boolean existsByUsernameSenderAndUsernameReceiver(String usernameSender, String usernameReceiver) {
ficou otimo!

2023-04-05 12:59 UTC, eduardaclx commented on src/main/java/br/com/shapeup/adapters/output/integration/profile/ProfilePictureAdapter.java
> +        });
argumento justo

2023-04-05 13:00 UTC, eduardaclx approved these changes

2023-04-05 13:04 UTC, merged